"""Declarative rules that turn a trait the prey has and the maw lacks into a candidate.

Every rule is a fact template. The judgment ("is this valuable for *this* maw?") is left to the
model; the rule only records what exists on each side, where to look, and a rough effort/risk.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TraitRule:
    key: str
    trait: str
    category: str
    title: str
    what: str
    serve_as: str
    effort: str
    risk: str
    value: float
    evidence: str = ""
    needs_maw: tuple[str, ...] = ()
    stack_bound: bool = False


TRAIT_RULES: tuple[TraitRule, ...] = (
    # --- ci --------------------------------------------------------------------------------
    TraitRule(
        "ci.workflows",
        "has_ci",
        "ci",
        "Set up continuous integration",
        "runs CI with {ci_provider} ({ci_workflows} workflows)",
        "pr",
        "M",
        "low",
        1.0,
        evidence="files:.github/workflows/*",
    ),
    TraitRule(
        "ci.cache",
        "ci_cache",
        "ci",
        "Cache dependencies in CI",
        "caches dependencies between CI runs",
        "pr",
        "S",
        "low",
        0.9,
        evidence="workflows:cache",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.matrix",
        "ci_matrix",
        "ci",
        "Test across a matrix of platforms and runtimes",
        "runs CI jobs on a matrix",
        "pr",
        "M",
        "low",
        0.8,
        evidence="workflows:matrix",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.concurrency",
        "ci_concurrency",
        "ci",
        "Cancel superseded CI runs with concurrency groups",
        "uses concurrency groups",
        "pr",
        "S",
        "low",
        0.7,
        evidence="workflows:concurrency",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.permissions",
        "ci_permissions",
        "ci",
        "Declare least-privilege workflow permissions",
        "declares permissions in workflows",
        "pr",
        "S",
        "low",
        0.85,
        evidence="workflows:permissions",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.timeouts",
        "ci_timeouts",
        "ci",
        "Set job timeouts",
        "sets timeout-minutes on jobs",
        "pr",
        "S",
        "low",
        0.6,
        evidence="workflows:timeouts",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.release-automation",
        "ci_release_automation",
        "ci",
        "Automate releases",
        "automates releases from tags or a release workflow",
        "issue",
        "M",
        "medium",
        0.7,
        evidence="workflows:release",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.schedule",
        "ci_schedule",
        "ci",
        "Add a scheduled CI run",
        "runs scheduled workflows",
        "issue",
        "S",
        "low",
        0.4,
        evidence="workflows:schedule",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.workflow-dispatch",
        "ci_workflow_dispatch",
        "ci",
        "Allow manual workflow runs",
        "allows workflow_dispatch",
        "pr",
        "S",
        "low",
        0.3,
        evidence="workflows:workflow_dispatch",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.reusable-workflows",
        "ci_reusable_workflows",
        "ci",
        "Factor CI into reusable workflows",
        "uses reusable workflows",
        "idea",
        "M",
        "low",
        0.4,
        evidence="workflows:reusable",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.windows-runner",
        "ci_windows_runner",
        "ci",
        "Test on Windows runners",
        "tests on Windows",
        "pr",
        "S",
        "medium",
        0.6,
        evidence="workflows:windows",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.macos-runner",
        "ci_macos_runner",
        "ci",
        "Test on macOS runners",
        "tests on macOS",
        "pr",
        "S",
        "medium",
        0.4,
        evidence="workflows:macos",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "ci.runs-tests",
        "ci_runs_tests",
        "ci",
        "Run the test suite in CI",
        "runs its tests in CI",
        "pr",
        "S",
        "low",
        0.9,
        evidence="workflows:tests",
        needs_maw=("has_ci", "has_tests"),
    ),
    TraitRule(
        "ci.runs-lint",
        "ci_runs_lint",
        "ci",
        "Run linters and type checkers in CI",
        "runs linters in CI",
        "pr",
        "S",
        "low",
        0.7,
        evidence="workflows:lint",
        needs_maw=("has_ci",),
    ),
    # --- security --------------------------------------------------------------------------
    TraitRule(
        "security.codeql",
        "ci_codeql",
        "security",
        "Run CodeQL analysis",
        "runs CodeQL",
        "pr",
        "S",
        "low",
        0.8,
        evidence="workflows:codeql",
        needs_maw=("has_ci",),
    ),
    TraitRule(
        "security.scanning",
        "ci_security_scanning",
        "security",
        "Add security scanning to CI",
        "runs security scanners ({ci_security_scanning})",
        "pr",
        "S",
        "low",
        0.7,
        evidence="workflows:security",
        needs_maw=("has_ci",),
    ),
    # --- tooling ---------------------------------------------------------------------------
    TraitRule(
        "tooling.dependabot",
        "has_dependabot",
        "tooling",
        "Enable Dependabot updates",
        "keeps dependencies fresh with Dependabot ({dependabot_ecosystems})",
        "pr",
        "S",
        "low",
        0.85,
        evidence="files:.github/dependabot.yml",
    ),
    TraitRule(
        "tooling.renovate",
        "has_renovate",
        "tooling",
        "Automate dependency updates with Renovate",
        "uses Renovate",
        "issue",
        "S",
        "low",
        0.6,
        evidence="files:renovate.json",
    ),
    TraitRule(
        "tooling.pre-commit",
        "has_precommit",
        "tooling",
        "Add pre-commit hooks",
        "runs pre-commit hooks",
        "pr",
        "S",
        "low",
        0.7,
        evidence="files:.pre-commit-config.yaml",
    ),
    TraitRule(
        "tooling.editorconfig",
        "has_editorconfig",
        "tooling",
        "Add an .editorconfig",
        "ships an .editorconfig",
        "pr",
        "S",
        "low",
        0.5,
        evidence="files:.editorconfig",
    ),
    TraitRule(
        "tooling.gitattributes",
        "has_gitattributes",
        "tooling",
        "Add a .gitattributes with line-ending rules",
        "ships a .gitattributes",
        "pr",
        "S",
        "low",
        0.4,
        evidence="files:.gitattributes",
    ),
    TraitRule(
        "tooling.devcontainer",
        "has_devcontainer",
        "tooling",
        "Provide a dev container",
        "ships a dev container",
        "issue",
        "M",
        "low",
        0.5,
        evidence="files:.devcontainer/*",
    ),
    TraitRule(
        "tooling.dockerfile",
        "has_dockerfile",
        "tooling",
        "Provide a Dockerfile",
        "ships a Dockerfile",
        "issue",
        "M",
        "medium",
        0.4,
        evidence="files:Dockerfile",
    ),
    TraitRule(
        "tooling.git-hooks",
        "has_husky",
        "tooling",
        "Add git hooks with husky",
        "runs git hooks via husky",
        "pr",
        "S",
        "low",
        0.5,
        evidence="files:.husky/*",
        stack_bound=True,
    ),
    TraitRule(
        "tooling.commitlint",
        "has_commitlint",
        "tooling",
        "Enforce commit message format with commitlint",
        "enforces commitlint",
        "pr",
        "S",
        "low",
        0.5,
        stack_bound=True,
    ),
    TraitRule(
        "tooling.lockfile",
        "has_lockfile",
        "tooling",
        "Commit a lock file",
        "commits a lock file ({lockfiles})",
        "pr",
        "S",
        "low",
        0.8,
        stack_bound=True,
    ),
    TraitRule(
        "tooling.nix",
        "has_nix",
        "tooling",
        "Provide a Nix development shell",
        "ships a Nix flake or shell",
        "idea",
        "M",
        "low",
        0.3,
        evidence="files:flake.nix",
    ),
    # --- hygiene ---------------------------------------------------------------------------
    TraitRule(
        "hygiene.readme",
        "has_readme",
        "hygiene",
        "Add a README",
        "has a README with sections {readme_sections}",
        "pr",
        "S",
        "low",
        1.0,
    ),
    TraitRule(
        "hygiene.license",
        "has_license",
        "hygiene",
        "Add a LICENSE file",
        "ships a LICENSE ({license_spdx})",
        "pr",
        "S",
        "low",
        0.9,
    ),
    TraitRule(
        "hygiene.contributing",
        "has_contributing",
        "hygiene",
        "Add a CONTRIBUTING guide",
        "ships a contributing guide",
        "pr",
        "S",
        "low",
        0.6,
        evidence="files:CONTRIBUTING*",
    ),
    TraitRule(
        "hygiene.code-of-conduct",
        "has_code_of_conduct",
        "hygiene",
        "Add a code of conduct",
        "ships a code of conduct",
        "pr",
        "S",
        "low",
        0.4,
        evidence="files:CODE_OF_CONDUCT*",
    ),
    TraitRule(
        "hygiene.security-md",
        "has_security_md",
        "hygiene",
        "Add a security policy (SECURITY.md)",
        "ships a security policy",
        "pr",
        "S",
        "low",
        0.7,
        evidence="files:SECURITY*",
    ),
    TraitRule(
        "hygiene.notice-file",
        "has_notice_file",
        "hygiene",
        "Record third-party attribution in a NOTICE file",
        "keeps a NOTICE file for third-party attribution",
        "pr",
        "S",
        "low",
        0.6,
        evidence="files:*NOTICE*",
    ),
    TraitRule(
        "hygiene.support-md",
        "has_support_md",
        "hygiene",
        "Add a SUPPORT.md",
        "ships a support guide",
        "pr",
        "S",
        "low",
        0.3,
        evidence="files:SUPPORT*",
    ),
    TraitRule(
        "hygiene.codeowners",
        "has_codeowners",
        "hygiene",
        "Add CODEOWNERS",
        "assigns owners with CODEOWNERS",
        "pr",
        "S",
        "low",
        0.5,
        evidence="files:**/CODEOWNERS",
    ),
    TraitRule(
        "hygiene.changelog",
        "has_changelog",
        "hygiene",
        "Keep a changelog",
        "keeps a changelog ({changelog_format})",
        "pr",
        "S",
        "low",
        0.6,
        evidence="files:CHANGELOG*",
    ),
    TraitRule(
        "hygiene.issue-templates",
        "has_issue_templates",
        "hygiene",
        "Add issue templates",
        "ships issue templates",
        "pr",
        "S",
        "low",
        0.5,
        evidence="files:.github/ISSUE_TEMPLATE/*",
    ),
    TraitRule(
        "hygiene.pr-template",
        "has_pr_template",
        "hygiene",
        "Add a pull request template",
        "ships a pull request template",
        "pr",
        "S",
        "low",
        0.5,
        evidence="files:.github/PULL_REQUEST_TEMPLATE*",
    ),
    TraitRule(
        "hygiene.funding",
        "has_funding",
        "hygiene",
        "Add FUNDING.yml",
        "ships a FUNDING.yml",
        "idea",
        "S",
        "low",
        0.2,
        evidence="files:.github/FUNDING.yml",
    ),
    TraitRule(
        "hygiene.citation",
        "has_citation",
        "hygiene",
        "Add a CITATION file",
        "ships a citation file",
        "idea",
        "S",
        "low",
        0.2,
        evidence="files:CITATION*",
    ),
    TraitRule(
        "hygiene.gitignore",
        "has_gitignore",
        "hygiene",
        "Add a .gitignore",
        "ships a .gitignore",
        "pr",
        "S",
        "low",
        0.7,
    ),
    # --- docs ------------------------------------------------------------------------------
    TraitRule(
        "docs.site",
        "has_docs_site",
        "docs",
        "Publish a documentation site",
        "publishes docs with {docs_site}",
        "issue",
        "L",
        "low",
        0.6,
    ),
    TraitRule(
        "docs.adr",
        "has_adr",
        "docs",
        "Record architecture decisions (ADRs)",
        "keeps architecture decision records",
        "issue",
        "S",
        "low",
        0.5,
    ),
    TraitRule(
        "docs.directory",
        "docs_dir",
        "docs",
        "Add a docs directory",
        "keeps documentation under {docs_dir}/",
        "issue",
        "M",
        "low",
        0.4,
    ),
    # --- ai-config -------------------------------------------------------------------------
    TraitRule(
        "ai-config.agents-md",
        "has_agents_md",
        "ai-config",
        "Add an AGENTS.md agent guide",
        "ships AGENTS.md",
        "pr",
        "S",
        "low",
        0.85,
        evidence="files:AGENTS.md",
    ),
    TraitRule(
        "ai-config.claude-md",
        "has_claude_md",
        "ai-config",
        "Add a CLAUDE.md",
        "ships CLAUDE.md",
        "pr",
        "S",
        "low",
        0.8,
        evidence="files:CLAUDE.md",
    ),
    TraitRule(
        "ai-config.cursor-rules",
        "has_cursor_rules",
        "ai-config",
        "Add Cursor rules",
        "ships Cursor rules",
        "pr",
        "S",
        "low",
        0.4,
        evidence="files:.cursorrules",
    ),
    TraitRule(
        "ai-config.copilot-instructions",
        "has_copilot_instructions",
        "ai-config",
        "Add Copilot instructions",
        "ships Copilot instructions",
        "pr",
        "S",
        "low",
        0.4,
        evidence="files:.github/copilot-instructions.md",
    ),
    TraitRule(
        "ai-config.gemini-md",
        "has_gemini_md",
        "ai-config",
        "Add a GEMINI.md",
        "ships GEMINI.md",
        "pr",
        "S",
        "low",
        0.3,
        evidence="files:GEMINI.md",
    ),
    TraitRule(
        "ai-config.llms-txt",
        "has_llms_txt",
        "ai-config",
        "Add an llms.txt",
        "ships llms.txt",
        "pr",
        "S",
        "low",
        0.4,
        evidence="files:llms.txt",
    ),
    TraitRule(
        "ai-config.claude-settings",
        "has_claude_settings",
        "ai-config",
        "Add project Claude Code settings",
        "ships .claude/settings.json",
        "issue",
        "S",
        "low",
        0.5,
        evidence="files:.claude/settings.json",
    ),
    TraitRule(
        "ai-config.skills",
        "has_skills",
        "ai-config",
        "Add agent skills",
        "ships {skills_count} agent skills",
        "issue",
        "M",
        "low",
        0.7,
    ),
    TraitRule(
        "ai-config.claude-agents",
        "has_claude_agents",
        "ai-config",
        "Add Claude Code subagents",
        "ships subagents",
        "issue",
        "M",
        "low",
        0.5,
        evidence="files:.claude/agents/*",
    ),
    TraitRule(
        "ai-config.claude-hooks",
        "has_claude_hooks",
        "ai-config",
        "Add Claude Code hooks",
        "uses hooks",
        "issue",
        "M",
        "low",
        0.5,
    ),
    TraitRule(
        "ai-config.claude-commands",
        "has_claude_commands",
        "ai-config",
        "Add Claude Code commands",
        "ships slash commands",
        "issue",
        "S",
        "low",
        0.4,
        evidence="files:.claude/commands/*",
    ),
    TraitRule(
        "ai-config.mcp",
        "has_mcp_config",
        "ai-config",
        "Add an MCP configuration",
        "configures MCP servers",
        "issue",
        "S",
        "low",
        0.5,
        evidence="files:.mcp.json",
    ),
    # --- tests -----------------------------------------------------------------------------
    TraitRule(
        "tests.suite",
        "has_tests",
        "tests",
        "Add a test suite",
        "has {test_files} test files ({test_frameworks})",
        "issue",
        "L",
        "medium",
        1.0,
    ),
    TraitRule(
        "tests.coverage",
        "coverage_configured",
        "tests",
        "Measure test coverage",
        "measures coverage",
        "pr",
        "S",
        "low",
        0.7,
        needs_maw=("has_tests",),
    ),
)

TEST_KIND_TRAITS: dict[str, tuple[str, str, str]] = {
    # trait -> (kind, effort, title)
    "has_e2e_tests": ("e2e", "L", "Add end-to-end tests"),
    "has_property_tests": ("property", "M", "Add property-based tests"),
    "has_snapshot_tests": ("snapshot", "M", "Add snapshot tests"),
    "has_fuzz_tests": ("fuzz", "L", "Add fuzz tests"),
    "has_mutation_tests": ("mutation", "M", "Add mutation testing"),
    "has_benchmarks": ("bench", "M", "Add benchmarks"),
    "has_integration_tests": ("integration", "M", "Add integration tests"),
}

# tool -> ecosystem (a maw can only adopt tools of an ecosystem it uses)
TOOL_ECOSYSTEM: dict[str, str] = {
    "eslint": "npm", "prettier": "npm", "biome": "npm", "oxlint": "npm", "stylelint": "npm",
    "typescript": "npm", "knip": "npm", "commitlint": "npm", "markdownlint": "npm",
    "cspell": "npm", "dependency-cruiser": "npm", "madge": "npm", "dprint": "npm",
    "ruff": "python", "ruff-format": "python", "black": "python", "isort": "python",
    "flake8": "python", "pylint": "python", "mypy": "python", "pyright": "python",
    "basedpyright": "python", "bandit": "python", "vulture": "python", "deptry": "python",
    "autopep8": "python", "yapf": "python", "pyre": "python", "ty": "python",
    "dotnet format": "dotnet", "csharpier": "dotnet",
    "golangci-lint": "go", "gofmt": "go", "clippy": "rust", "rustfmt": "rust",
    "rubocop": "ruby", "shfmt": "shell", "htmlhint": "npm", "flow": "npm",
}  # fmt: skip

# notable dependencies worth a card of their own (name -> short description)
NOTABLE_DEPS: dict[str, dict[str, str]] = {
    "npm": {
        "vite": "fast dev server and bundler",
        "tsup": "bundler for TypeScript libraries",
        "turbo": "monorepo task runner with caching",
        "@changesets/cli": "versioning and changelog automation for monorepos",
        "husky": "git hooks",
        "lint-staged": "run linters on staged files",
        "zod": "schema validation with static types",
        "msw": "API mocking for tests",
        "tsx": "run TypeScript directly",
        "vitest": "test runner",
        "@playwright/test": "browser end-to-end tests",
        "fast-check": "property-based testing",
        "knip": "find unused files, exports and dependencies",
    },
    "python": {
        "pre-commit": "git hook framework",
        "tox": "test automation across environments",
        "nox": "test automation with Python sessions",
        "hypothesis": "property-based testing",
        "pytest-cov": "coverage for pytest",
        "pydantic": "data validation",
        "typer": "CLI framework",
        "rich": "terminal formatting",
        "httpx": "HTTP client",
        "mkdocs-material": "documentation site theme",
    },
    "dotnet": {
        "BenchmarkDotNet": "benchmarks",
        "FluentAssertions": "expressive test assertions",
        "coverlet.collector": "coverage collection",
        "Verify.Xunit": "snapshot testing",
        "FsCheck": "property-based testing",
        "NSubstitute": "mocking",
        "Microsoft.CodeAnalysis.NetAnalyzers": "static analysis",
    },
    "rust": {"criterion": "benchmarks", "proptest": "property-based testing", "insta": "snapshots"},
    "go": {"github.com/stretchr/testify": "test assertions"},
}
